package com.vet.view;

import com.vet.view.table.impl.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

/**
 * Vet's project Main frame
 * @author Nicolas Canova
 */
public class Frame extends JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        clientePanel = new javax.swing.JPanel();
        clienteTabbedPane = new javax.swing.JTabbedPane();
        cadastrarClientePanel = new javax.swing.JPanel();
        nomeClienteLabel = new javax.swing.JLabel();
        nomeClienteTextField = new javax.swing.JTextField();
        cepClienteLabel = new javax.swing.JLabel();
        cepClienteTextField = new javax.swing.JTextField();
        enderecoClienteLabel = new javax.swing.JLabel();
        enderecoClienteTextField = new javax.swing.JTextField();
        telefoneClienteLabel = new javax.swing.JLabel();
        telefoneClienteTextField = new javax.swing.JTextField();
        emailClienteTextField = new javax.swing.JTextField();
        emailClienteLabel = new javax.swing.JLabel();
        cadastrarClienteButton = new javax.swing.JButton();
        atualizarClientePanel = new javax.swing.JPanel();
        atualizarClienteLabel = new javax.swing.JLabel();
        atualizarClienteComboBox = new javax.swing.JComboBox<>();
        atualizarNomeClienteLabel = new javax.swing.JLabel();
        atualizarNomeClienteTextField = new javax.swing.JTextField();
        atualizarCepClienteLabel = new javax.swing.JLabel();
        atualizarCepClienteTextField = new javax.swing.JTextField();
        atualizarEnderecoClienteLabel = new javax.swing.JLabel();
        atualizarEnderecoClienteTextField = new javax.swing.JTextField();
        atualizarTelefoneClienteLabel = new javax.swing.JLabel();
        atualizarTelefoneClienteTextField = new javax.swing.JTextField();
        atualizarEmailClienteLabel = new javax.swing.JLabel();
        atualizarEmailClienteTextField = new javax.swing.JTextField();
        atualizarClienteButton = new javax.swing.JButton();
        clienteScrollPane = new javax.swing.JScrollPane();
        clienteTable = new javax.swing.JTable();
        animalPanel = new javax.swing.JPanel();
        animalTabbedPane = new javax.swing.JTabbedPane();
        cadastrarAnimalPanel = new javax.swing.JPanel();
        especieAnimalLabel = new javax.swing.JLabel();
        nomeAnimalLabel = new javax.swing.JLabel();
        tutorLabel = new javax.swing.JLabel();
        idadeAnimalLabel = new javax.swing.JLabel();
        sexoAnimalLabel = new javax.swing.JLabel();
        nomeAnimalTextField = new javax.swing.JTextField();
        cadastrarAnimalButton = new javax.swing.JButton();
        sexoAnimalComboBox = new javax.swing.JComboBox<>();
        idadeAnimalSpinner = new javax.swing.JSpinner();
        especieAnimalComboBox = new javax.swing.JComboBox<>();
        tutorComboBox = new javax.swing.JComboBox<>();
        cadastrarEspeciesPanel = new javax.swing.JPanel();
        nomeEspecieLabel = new javax.swing.JLabel();
        nomeEspecieTextField = new javax.swing.JTextField();
        cadastrarEspecieButton = new javax.swing.JButton();
        atualizarAnimalPanel = new javax.swing.JPanel();
        atualizarAnimalLabel = new javax.swing.JLabel();
        atualizarAnimalComboBox = new javax.swing.JComboBox<>();
        atualizarTutorLabel = new javax.swing.JLabel();
        atualizarTutorComboBox = new javax.swing.JComboBox<>();
        atualizarEspecieLabel = new javax.swing.JLabel();
        atualizarEspecieComboBox = new javax.swing.JComboBox<>();
        atualizarNomeAnimalLabel = new javax.swing.JLabel();
        atualizarNomeAnimalTextField = new javax.swing.JTextField();
        atualizarIdadeAnimalLabel = new javax.swing.JLabel();
        atualizarIdadeAnimalSpinner = new javax.swing.JSpinner();
        atualizarSexoAnimalLabel = new javax.swing.JLabel();
        atualizarSexoAnimalComboBox = new javax.swing.JComboBox<>();
        atualizarAnimalButton = new javax.swing.JButton();
        animalScrollPane = new javax.swing.JScrollPane();
        animalTable = new javax.swing.JTable();
        veterinarioPanel = new javax.swing.JPanel();
        veterinarioTabbedPane = new javax.swing.JTabbedPane();
        cadastrarVeterinario = new javax.swing.JPanel();
        nomeVeterinarioLabel = new javax.swing.JLabel();
        nomeVeterinarioTextField = new javax.swing.JTextField();
        cepVeterinarioLabel = new javax.swing.JLabel();
        cepVeterinarioTextField = new javax.swing.JTextField();
        enderecoVeterinarioLabel = new javax.swing.JLabel();
        enderecoVeterinarioTextField = new javax.swing.JTextField();
        telefoneVeterinarioLabel = new javax.swing.JLabel();
        telefoneVeterinarioTextField = new javax.swing.JTextField();
        emailVeterinarioTextField = new javax.swing.JTextField();
        emailVeterinarioLabel = new javax.swing.JLabel();
        cadastrarVeterinarioButton = new javax.swing.JButton();
        atualizarVeterinario = new javax.swing.JPanel();
        atualizarVeterinarioComboBox = new javax.swing.JComboBox<>();
        atualizarVeterinarioLabel = new javax.swing.JLabel();
        atualizarVeterinarioButton = new javax.swing.JButton();
        atualizarEmailVeterinarioTextField = new javax.swing.JTextField();
        atualizarEmailVeterinarioLabel = new javax.swing.JLabel();
        atualizarTelefoneVeterinarioTextField = new javax.swing.JTextField();
        atualizarTelefoneVeterinarioLabel = new javax.swing.JLabel();
        atualizarEnderecoVeterinarioTextField = new javax.swing.JTextField();
        atualizarEnderecoVeterinarioLabel = new javax.swing.JLabel();
        atualizarCepVeterinarioTextField = new javax.swing.JTextField();
        atualizarCepVeterinarioLabel = new javax.swing.JLabel();
        atualizarNomeVeterinarioTextField = new javax.swing.JTextField();
        atualizarNomeVeterinarioLabel = new javax.swing.JLabel();
        veterinarioScrollPane = new javax.swing.JScrollPane();
        veterinarioTable = new javax.swing.JTable();
        consultaPanel = new javax.swing.JPanel();
        consultaTabbedPane = new javax.swing.JTabbedPane();
        cadastrarConsulta = new javax.swing.JPanel();
        dataConsultaLabel = new javax.swing.JLabel();
        relatoConsultaLabel = new javax.swing.JLabel();
        veterinarioConsultaLabel = new javax.swing.JLabel();
        cadastrarConsultaButton = new javax.swing.JButton();
        tratamentoConsultaLabel = new javax.swing.JLabel();
        tratamentoConsultaComboBox = new javax.swing.JComboBox<>();
        veterinarioConsultaComboBox = new javax.swing.JComboBox<>();
        diaConsultaSpinner = new javax.swing.JSpinner();
        mesConsultaSpinner = new javax.swing.JSpinner();
        anoConsultaSpinner = new javax.swing.JSpinner();
        diaConsultaLabel = new javax.swing.JLabel();
        mesConsultaLabel = new javax.swing.JLabel();
        anoConsultaLabel = new javax.swing.JLabel();
        relatoCadastrarConsultaScrollPane = new javax.swing.JScrollPane();
        relatoConsultaTextArea = new javax.swing.JTextArea();
        consultaScrollPane = new javax.swing.JScrollPane();
        consultaTable = new javax.swing.JTable();
        examePanel = new javax.swing.JPanel();
        exameTabbedPane = new javax.swing.JTabbedPane();
        cadastrarExamePanel = new javax.swing.JPanel();
        descricaoExameLabel = new javax.swing.JLabel();
        consultaExameLabel = new javax.swing.JLabel();
        cadastrarExameButton = new javax.swing.JButton();
        consultaExameComboBox = new javax.swing.JComboBox<>();
        descricaoCadastrarExamePane = new javax.swing.JScrollPane();
        descricaoExameTextArea = new javax.swing.JTextArea();
        exameScrollPane = new javax.swing.JScrollPane();
        exameTable = new javax.swing.JTable();
        tratamentoPanel = new javax.swing.JPanel();
        tratamentoTabbedPane = new javax.swing.JTabbedPane();
        cadastrarTratamentoPanel = new javax.swing.JPanel();
        dataFimTratamentoLabel = new javax.swing.JLabel();
        animalTratamentoLabel = new javax.swing.JLabel();
        animalTratamentoComboBox = new javax.swing.JComboBox<>();
        dataInicioLabel = new javax.swing.JLabel();
        cadastrarTratamentoButton = new javax.swing.JButton();
        diaFimTratamentoSpinner = new javax.swing.JSpinner();
        diaFimTratamentoLabel = new javax.swing.JLabel();
        mesFimTratamentoLabel = new javax.swing.JLabel();
        mesFimTratamentoSpinner = new javax.swing.JSpinner();
        anoFimTratamentoLabel = new javax.swing.JLabel();
        anoFimTratamentoSpinner = new javax.swing.JSpinner();
        diaInicioTratamentoSpinner = new javax.swing.JSpinner();
        diaInicioTratamentoLabel = new javax.swing.JLabel();
        mesInicioTratamentoLabel = new javax.swing.JLabel();
        mesInicioTratamentoSpinner = new javax.swing.JSpinner();
        anoInicioTratamentoLabel = new javax.swing.JLabel();
        anoInicioTratamentoSpinner = new javax.swing.JSpinner();
        tratamentoScrollPane = new javax.swing.JScrollPane();
        tratamentoTable = new javax.swing.JTable();
        logoIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeClienteLabel.setText("Nome Cliente");

        cepClienteLabel.setText("CEP Cliente");

        enderecoClienteLabel.setText("Endereço Cliente");

        telefoneClienteLabel.setText("Telefone Cliente");

        emailClienteLabel.setText("Email Cliente");

        cadastrarClienteButton.setText("Cadastrar");

        javax.swing.GroupLayout cadastrarClientePanelLayout = new javax.swing.GroupLayout(cadastrarClientePanel);
        cadastrarClientePanel.setLayout(cadastrarClientePanelLayout);
        cadastrarClientePanelLayout.setHorizontalGroup(
            cadastrarClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarClientePanelLayout.createSequentialGroup()
                .addGroup(cadastrarClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastrarClientePanelLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(cadastrarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastrarClientePanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(cadastrarClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastrarClientePanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(emailClienteLabel))
                            .addGroup(cadastrarClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailClienteTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telefoneClienteTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enderecoClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cepClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomeClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cadastrarClientePanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(cadastrarClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cepClienteLabel)
                                            .addComponent(enderecoClienteLabel)
                                            .addComponent(telefoneClienteLabel)))))))
                    .addGroup(cadastrarClientePanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(nomeClienteLabel)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        cadastrarClientePanelLayout.setVerticalGroup(
            cadastrarClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarClientePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(nomeClienteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cepClienteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cepClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoClienteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoneClienteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoneClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailClienteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastrarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        clienteTabbedPane.addTab("Cadastrar Cliente", cadastrarClientePanel);

        atualizarClienteLabel.setText("Cliente");

        atualizarClienteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João da Silva", "Item 2", "Item 3", "Item 4" }));
        atualizarClienteComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarClienteComboBoxActionPerformed(evt);
            }
        });

        atualizarNomeClienteLabel.setText("Nome Cliente");

        atualizarNomeClienteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarNomeClienteTextFieldActionPerformed(evt);
            }
        });

        atualizarCepClienteLabel.setText("CEP Cliente");

        atualizarEnderecoClienteLabel.setText("Endereço Cliente");

        atualizarTelefoneClienteLabel.setText("Telefone Cliente");

        atualizarEmailClienteLabel.setText("Email Cliente");

        atualizarClienteButton.setText("Atualizar");

        javax.swing.GroupLayout atualizarClientePanelLayout = new javax.swing.GroupLayout(atualizarClientePanel);
        atualizarClientePanel.setLayout(atualizarClientePanelLayout);
        atualizarClientePanelLayout.setHorizontalGroup(
            atualizarClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, atualizarClientePanelLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(atualizarClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(atualizarClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(atualizarClienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(atualizarClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atualizarEmailClienteTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atualizarTelefoneClienteTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, atualizarClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(atualizarEnderecoClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(atualizarCepClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(atualizarNomeClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(atualizarClientePanelLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(atualizarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(atualizarClientePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(atualizarClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atualizarNomeClienteLabel)
                            .addComponent(atualizarCepClienteLabel)
                            .addComponent(atualizarEnderecoClienteLabel)
                            .addComponent(atualizarTelefoneClienteLabel)
                            .addComponent(atualizarEmailClienteLabel))))
                .addGap(52, 52, 52))
            .addGroup(atualizarClientePanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(atualizarClienteLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        atualizarClientePanelLayout.setVerticalGroup(
            atualizarClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atualizarClientePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(atualizarClienteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarClienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarNomeClienteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarNomeClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarCepClienteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarCepClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarEnderecoClienteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarEnderecoClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarTelefoneClienteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarTelefoneClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarEmailClienteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarEmailClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(atualizarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        clienteTabbedPane.addTab("Atualizar cliente", atualizarClientePanel);

        clienteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CEP", "Endereço", "Telefone", "Email"
            }
        ));
        clienteScrollPane.setViewportView(clienteTable);

        javax.swing.GroupLayout clientePanelLayout = new javax.swing.GroupLayout(clientePanel);
        clientePanel.setLayout(clientePanelLayout);
        clientePanelLayout.setHorizontalGroup(
            clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clienteScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clienteTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        clientePanelLayout.setVerticalGroup(
            clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clienteTabbedPane)
            .addGroup(clientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clienteScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Cliente", clientePanel);

        especieAnimalLabel.setText("Espécie");

        nomeAnimalLabel.setText("Nome Animal");

        tutorLabel.setText("Cliente tutor do Animal");

        idadeAnimalLabel.setText("Idade Animal");

        sexoAnimalLabel.setText("Sexo Animal");

        cadastrarAnimalButton.setText("Cadastrar");

        sexoAnimalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        sexoAnimalComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoAnimalComboBoxActionPerformed(evt);
            }
        });

        especieAnimalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João da Silva", "Item 2", "Item 3", "Item 4" }));
        especieAnimalComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especieAnimalComboBoxActionPerformed(evt);
            }
        });

        tutorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João da Silva", "Item 2", "Item 3", "Item 4" }));
        tutorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastrarAnimalPanelLayout = new javax.swing.GroupLayout(cadastrarAnimalPanel);
        cadastrarAnimalPanel.setLayout(cadastrarAnimalPanelLayout);
        cadastrarAnimalPanelLayout.setHorizontalGroup(
            cadastrarAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarAnimalPanelLayout.createSequentialGroup()
                .addGroup(cadastrarAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastrarAnimalPanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(cadastrarAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeAnimalTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(especieAnimalComboBox, 0, 300, Short.MAX_VALUE)
                            .addComponent(tutorComboBox, 0, 300, Short.MAX_VALUE)
                            .addGroup(cadastrarAnimalPanelLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(cadastrarAnimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cadastrarAnimalPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(especieAnimalLabel))
                            .addGroup(cadastrarAnimalPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nomeAnimalLabel))
                            .addGroup(cadastrarAnimalPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(idadeAnimalLabel))
                            .addComponent(idadeAnimalSpinner)
                            .addComponent(sexoAnimalComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sexoAnimalLabel)))
                    .addGroup(cadastrarAnimalPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(tutorLabel)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        cadastrarAnimalPanelLayout.setVerticalGroup(
            cadastrarAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarAnimalPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tutorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tutorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(especieAnimalLabel)
                .addGap(12, 12, 12)
                .addComponent(especieAnimalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeAnimalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeAnimalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idadeAnimalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idadeAnimalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sexoAnimalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sexoAnimalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastrarAnimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        animalTabbedPane.addTab("Cadastrar Animal", cadastrarAnimalPanel);

        nomeEspecieLabel.setText("Nome Espécie");

        cadastrarEspecieButton.setText("Cadastrar");

        javax.swing.GroupLayout cadastrarEspeciesPanelLayout = new javax.swing.GroupLayout(cadastrarEspeciesPanel);
        cadastrarEspeciesPanel.setLayout(cadastrarEspeciesPanelLayout);
        cadastrarEspeciesPanelLayout.setHorizontalGroup(
            cadastrarEspeciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarEspeciesPanelLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(cadastrarEspeciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeEspecieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cadastrarEspeciesPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(cadastrarEspecieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
            .addGroup(cadastrarEspeciesPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(nomeEspecieLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cadastrarEspeciesPanelLayout.setVerticalGroup(
            cadastrarEspeciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarEspeciesPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(nomeEspecieLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeEspecieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastrarEspecieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        animalTabbedPane.addTab("Cadastrar Especies", cadastrarEspeciesPanel);

        atualizarAnimalLabel.setText("Animal");

        atualizarAnimalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João da Silva", "Item 2", "Item 3", "Item 4" }));
        atualizarAnimalComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarAnimalComboBoxActionPerformed(evt);
            }
        });

        atualizarTutorLabel.setText("Cliente tutor do Animal");

        atualizarTutorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João da Silva", "Item 2", "Item 3", "Item 4" }));
        atualizarTutorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarTutorComboBoxActionPerformed(evt);
            }
        });

        atualizarEspecieLabel.setText("Espécie");

        atualizarEspecieComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João da Silva", "Item 2", "Item 3", "Item 4" }));
        atualizarEspecieComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarEspecieComboBoxActionPerformed(evt);
            }
        });

        atualizarNomeAnimalLabel.setText("Nome Animal");

        atualizarIdadeAnimalLabel.setText("Idade Animal");

        atualizarSexoAnimalLabel.setText("Sexo Animal");

        atualizarSexoAnimalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        atualizarAnimalButton.setText("Atualizar");

        javax.swing.GroupLayout atualizarAnimalPanelLayout = new javax.swing.GroupLayout(atualizarAnimalPanel);
        atualizarAnimalPanel.setLayout(atualizarAnimalPanelLayout);
        atualizarAnimalPanelLayout.setHorizontalGroup(
            atualizarAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atualizarAnimalPanelLayout.createSequentialGroup()
                .addGroup(atualizarAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(atualizarAnimalPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(atualizarAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(atualizarNomeAnimalTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(atualizarEspecieComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 300, Short.MAX_VALUE)
                            .addComponent(atualizarIdadeAnimalSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atualizarTutorComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 300, Short.MAX_VALUE)
                            .addComponent(atualizarAnimalComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(atualizarSexoAnimalComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, atualizarAnimalPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(atualizarAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(atualizarNomeAnimalLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(atualizarIdadeAnimalLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(atualizarSexoAnimalLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(atualizarTutorLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(atualizarEspecieLabel, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(atualizarAnimalPanelLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(atualizarAnimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(atualizarAnimalPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(atualizarAnimalLabel)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        atualizarAnimalPanelLayout.setVerticalGroup(
            atualizarAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atualizarAnimalPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(atualizarAnimalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarAnimalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarTutorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarTutorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarEspecieLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(atualizarEspecieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarNomeAnimalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarNomeAnimalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarIdadeAnimalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarIdadeAnimalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarSexoAnimalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarSexoAnimalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(atualizarAnimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        animalTabbedPane.addTab("Atualizar Animal", atualizarAnimalPanel);

        animalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Tutor", "Idade", "Sexo", "Espécie"
            }
        ));
        animalScrollPane.setViewportView(animalTable);

        javax.swing.GroupLayout animalPanelLayout = new javax.swing.GroupLayout(animalPanel);
        animalPanel.setLayout(animalPanelLayout);
        animalPanelLayout.setHorizontalGroup(
            animalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, animalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(animalScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(animalTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        animalPanelLayout.setVerticalGroup(
            animalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(animalTabbedPane)
            .addGroup(animalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(animalScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Animal", animalPanel);

        nomeVeterinarioLabel.setText("Nome Veterinário");

        nomeVeterinarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeVeterinarioTextFieldActionPerformed(evt);
            }
        });

        cepVeterinarioLabel.setText("CEP Veterinário");

        enderecoVeterinarioLabel.setText("Endereço Veterinário");

        telefoneVeterinarioLabel.setText("Telefone Veterinário");

        emailVeterinarioLabel.setText("Email Veterinário");

        cadastrarVeterinarioButton.setText("Cadastrar");

        javax.swing.GroupLayout cadastrarVeterinarioLayout = new javax.swing.GroupLayout(cadastrarVeterinario);
        cadastrarVeterinario.setLayout(cadastrarVeterinarioLayout);
        cadastrarVeterinarioLayout.setHorizontalGroup(
            cadastrarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarVeterinarioLayout.createSequentialGroup()
                .addGroup(cadastrarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastrarVeterinarioLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(cadastrarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailVeterinarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefoneVeterinarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cepVeterinarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeVeterinarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enderecoVeterinarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cadastrarVeterinarioLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(cadastrarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cepVeterinarioLabel)
                                    .addComponent(enderecoVeterinarioLabel)
                                    .addComponent(telefoneVeterinarioLabel)
                                    .addComponent(emailVeterinarioLabel)))))
                    .addGroup(cadastrarVeterinarioLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(cadastrarVeterinarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastrarVeterinarioLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(nomeVeterinarioLabel)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        cadastrarVeterinarioLayout.setVerticalGroup(
            cadastrarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarVeterinarioLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(nomeVeterinarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeVeterinarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cepVeterinarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cepVeterinarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoVeterinarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoVeterinarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoneVeterinarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoneVeterinarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailVeterinarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailVeterinarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadastrarVeterinarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        veterinarioTabbedPane.addTab("Cadastrar Veterinário", cadastrarVeterinario);

        atualizarVeterinarioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João da Silva", "Item 2", "Item 3", "Item 4" }));
        atualizarVeterinarioComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarVeterinarioComboBoxActionPerformed(evt);
            }
        });

        atualizarVeterinarioLabel.setText("Veterinário");

        atualizarVeterinarioButton.setText("Atualizar");

        atualizarEmailVeterinarioLabel.setText("Email Veterinário");

        atualizarTelefoneVeterinarioLabel.setText("Telefone Veterinário");

        atualizarEnderecoVeterinarioLabel.setText("Endereço Veterinário");

        atualizarCepVeterinarioLabel.setText("CEP Veterinário");

        atualizarNomeVeterinarioLabel.setText("Nome Veterinário");

        javax.swing.GroupLayout atualizarVeterinarioLayout = new javax.swing.GroupLayout(atualizarVeterinario);
        atualizarVeterinario.setLayout(atualizarVeterinarioLayout);
        atualizarVeterinarioLayout.setHorizontalGroup(
            atualizarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atualizarVeterinarioLayout.createSequentialGroup()
                .addGroup(atualizarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(atualizarVeterinarioLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(atualizarVeterinarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(atualizarVeterinarioLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(atualizarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(atualizarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(atualizarEmailVeterinarioTextField)
                                .addComponent(atualizarTelefoneVeterinarioTextField)
                                .addComponent(atualizarCepVeterinarioTextField)
                                .addComponent(atualizarNomeVeterinarioTextField)
                                .addComponent(atualizarEnderecoVeterinarioTextField)
                                .addComponent(atualizarVeterinarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(atualizarVeterinarioLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(atualizarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(atualizarNomeVeterinarioLabel)
                                    .addComponent(atualizarCepVeterinarioLabel)
                                    .addComponent(atualizarEnderecoVeterinarioLabel)
                                    .addComponent(atualizarTelefoneVeterinarioLabel)
                                    .addComponent(atualizarEmailVeterinarioLabel)))))
                    .addGroup(atualizarVeterinarioLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(atualizarVeterinarioLabel)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        atualizarVeterinarioLayout.setVerticalGroup(
            atualizarVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atualizarVeterinarioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(atualizarVeterinarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarVeterinarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarNomeVeterinarioLabel)
                .addGap(12, 12, 12)
                .addComponent(atualizarNomeVeterinarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarCepVeterinarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarCepVeterinarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarEnderecoVeterinarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarEnderecoVeterinarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarTelefoneVeterinarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarTelefoneVeterinarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarEmailVeterinarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarEmailVeterinarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(atualizarVeterinarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        veterinarioTabbedPane.addTab("Atualizar Veterinário", atualizarVeterinario);

        veterinarioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CEP", "Endereço", "Telefone", "Email"
            }
        ));
        veterinarioScrollPane.setViewportView(veterinarioTable);
        if (veterinarioTable.getColumnModel().getColumnCount() > 0) {
            veterinarioTable.getColumnModel().getColumn(3).setHeaderValue("Veterinário");
            veterinarioTable.getColumnModel().getColumn(4).setHeaderValue("Tratamento");
            veterinarioTable.getColumnModel().getColumn(5).setHeaderValue("Email");
        }

        javax.swing.GroupLayout veterinarioPanelLayout = new javax.swing.GroupLayout(veterinarioPanel);
        veterinarioPanel.setLayout(veterinarioPanelLayout);
        veterinarioPanelLayout.setHorizontalGroup(
            veterinarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, veterinarioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(veterinarioScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(veterinarioTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        veterinarioPanelLayout.setVerticalGroup(
            veterinarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(veterinarioTabbedPane)
            .addGroup(veterinarioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(veterinarioScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Veterinário", veterinarioPanel);

        dataConsultaLabel.setText("Data");

        relatoConsultaLabel.setText("Relato consulta");

        veterinarioConsultaLabel.setText("Veterinário");

        cadastrarConsultaButton.setText("Cadastrar");

        tratamentoConsultaLabel.setText("Tratamento");

        tratamentoConsultaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João da Silva", "Item 2", "Item 3", "Item 4" }));
        tratamentoConsultaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratamentoConsultaComboBoxActionPerformed(evt);
            }
        });

        veterinarioConsultaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João da Silva", "Item 2", "Item 3", "Item 4" }));
        veterinarioConsultaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veterinarioConsultaComboBoxActionPerformed(evt);
            }
        });

        diaConsultaSpinner.setMinimumSize(new java.awt.Dimension(80, 22));

        mesConsultaSpinner.setMinimumSize(new java.awt.Dimension(80, 22));

        anoConsultaSpinner.setMinimumSize(new java.awt.Dimension(80, 22));

        diaConsultaLabel.setText("Dia");

        mesConsultaLabel.setText("Mês");

        anoConsultaLabel.setText("Ano");

        relatoConsultaTextArea.setColumns(20);
        relatoConsultaTextArea.setRows(5);
        relatoCadastrarConsultaScrollPane.setViewportView(relatoConsultaTextArea);

        javax.swing.GroupLayout cadastrarConsultaLayout = new javax.swing.GroupLayout(cadastrarConsulta);
        cadastrarConsulta.setLayout(cadastrarConsultaLayout);
        cadastrarConsultaLayout.setHorizontalGroup(
            cadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarConsultaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(cadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tratamentoConsultaComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(relatoCadastrarConsultaScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastrarConsultaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(cadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(relatoConsultaLabel)
                            .addComponent(tratamentoConsultaLabel)
                            .addComponent(veterinarioConsultaLabel)
                            .addComponent(dataConsultaLabel)))
                    .addComponent(veterinarioConsultaComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(cadastrarConsultaLayout.createSequentialGroup()
                .addGroup(cadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastrarConsultaLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(cadastrarConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastrarConsultaLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(cadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(diaConsultaLabel)
                            .addComponent(diaConsultaSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(cadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mesConsultaSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(mesConsultaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(cadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(anoConsultaSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(anoConsultaLabel))))
                .addGap(117, 117, 117))
        );
        cadastrarConsultaLayout.setVerticalGroup(
            cadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarConsultaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(cadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaConsultaLabel)
                    .addComponent(mesConsultaLabel)
                    .addComponent(anoConsultaLabel)
                    .addComponent(dataConsultaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaConsultaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesConsultaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoConsultaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(relatoConsultaLabel)
                .addGap(11, 11, 11)
                .addComponent(relatoCadastrarConsultaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tratamentoConsultaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tratamentoConsultaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(veterinarioConsultaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(veterinarioConsultaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastrarConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        consultaTabbedPane.addTab("Cadastrar Consulta", cadastrarConsulta);

        consultaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Data", "Relato", "Veterinário", "Tratamento"
            }
        ));
        consultaScrollPane.setViewportView(consultaTable);
        if (consultaTable.getColumnModel().getColumnCount() > 0) {
            consultaTable.getColumnModel().getColumn(3).setHeaderValue("Veterinário");
            consultaTable.getColumnModel().getColumn(4).setHeaderValue("Tratamento");
        }

        javax.swing.GroupLayout consultaPanelLayout = new javax.swing.GroupLayout(consultaPanel);
        consultaPanel.setLayout(consultaPanelLayout);
        consultaPanelLayout.setHorizontalGroup(
            consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultaTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        consultaPanelLayout.setVerticalGroup(
            consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(consultaTabbedPane)
            .addGroup(consultaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Consulta", consultaPanel);

        descricaoExameLabel.setText("Descrição");

        consultaExameLabel.setText("Consulta");

        cadastrarExameButton.setText("Cadastrar");

        consultaExameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João da Silva", "Item 2", "Item 3", "Item 4" }));
        consultaExameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaExameComboBoxActionPerformed(evt);
            }
        });

        descricaoExameTextArea.setColumns(20);
        descricaoExameTextArea.setRows(5);
        descricaoCadastrarExamePane.setViewportView(descricaoExameTextArea);

        javax.swing.GroupLayout cadastrarExamePanelLayout = new javax.swing.GroupLayout(cadastrarExamePanel);
        cadastrarExamePanel.setLayout(cadastrarExamePanelLayout);
        cadastrarExamePanelLayout.setHorizontalGroup(
            cadastrarExamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarExamePanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(descricaoExameLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarExamePanelLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(cadastrarExamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastrarExamePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(consultaExameLabel))
                    .addGroup(cadastrarExamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(descricaoCadastrarExamePane, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(consultaExameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(cadastrarExamePanelLayout.createSequentialGroup()
                            .addComponent(cadastrarExameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(103, 103, 103))))
                .addGap(58, 58, 58))
        );
        cadastrarExamePanelLayout.setVerticalGroup(
            cadastrarExamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarExamePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(descricaoExameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricaoCadastrarExamePane, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultaExameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultaExameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastrarExameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        exameTabbedPane.addTab("Cadastrar Exame", cadastrarExamePanel);

        exameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Descrição", "Consulta"
            }
        ));
        exameScrollPane.setViewportView(exameTable);

        javax.swing.GroupLayout examePanelLayout = new javax.swing.GroupLayout(examePanel);
        examePanel.setLayout(examePanelLayout);
        examePanelLayout.setHorizontalGroup(
            examePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, examePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exameScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exameTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        examePanelLayout.setVerticalGroup(
            examePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exameTabbedPane)
            .addGroup(examePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exameScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Exame", examePanel);

        dataFimTratamentoLabel.setText("Data fim");

        animalTratamentoLabel.setText("Animal");

        animalTratamentoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João da Silva", "Item 2", "Item 3", "Item 4" }));
        animalTratamentoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalTratamentoComboBoxActionPerformed(evt);
            }
        });

        dataInicioLabel.setText("Data Início");

        cadastrarTratamentoButton.setText("Cadastrar");

        diaFimTratamentoSpinner.setMinimumSize(new java.awt.Dimension(80, 22));

        diaFimTratamentoLabel.setText("Dia");

        mesFimTratamentoLabel.setText("Mês");

        mesFimTratamentoSpinner.setMinimumSize(new java.awt.Dimension(80, 22));

        anoFimTratamentoLabel.setText("Ano");

        anoFimTratamentoSpinner.setMinimumSize(new java.awt.Dimension(80, 22));

        diaInicioTratamentoSpinner.setMinimumSize(new java.awt.Dimension(80, 22));

        diaInicioTratamentoLabel.setText("Dia");

        mesInicioTratamentoLabel.setText("Mês");

        mesInicioTratamentoSpinner.setMinimumSize(new java.awt.Dimension(80, 22));

        anoInicioTratamentoLabel.setText("Ano");

        anoInicioTratamentoSpinner.setMinimumSize(new java.awt.Dimension(80, 22));

        javax.swing.GroupLayout cadastrarTratamentoPanelLayout = new javax.swing.GroupLayout(cadastrarTratamentoPanel);
        cadastrarTratamentoPanel.setLayout(cadastrarTratamentoPanelLayout);
        cadastrarTratamentoPanelLayout.setHorizontalGroup(
            cadastrarTratamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarTratamentoPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(cadastrarTratamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastrarTratamentoPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(cadastrarTratamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastrarTratamentoPanelLayout.createSequentialGroup()
                                .addGroup(cadastrarTratamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cadastrarTratamentoPanelLayout.createSequentialGroup()
                                        .addComponent(dataInicioLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                        .addComponent(diaInicioTratamentoLabel))
                                    .addComponent(diaInicioTratamentoSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(cadastrarTratamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cadastrarTratamentoPanelLayout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(mesInicioTratamentoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(anoInicioTratamentoLabel))
                                    .addGroup(cadastrarTratamentoPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mesInicioTratamentoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(anoInicioTratamentoSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                            .addComponent(animalTratamentoLabel)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarTratamentoPanelLayout.createSequentialGroup()
                                .addGroup(cadastrarTratamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(cadastrarTratamentoPanelLayout.createSequentialGroup()
                                        .addComponent(dataFimTratamentoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(diaFimTratamentoLabel))
                                    .addComponent(diaFimTratamentoSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cadastrarTratamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mesFimTratamentoSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mesFimTratamentoLabel))
                                .addGap(6, 6, 6)
                                .addGroup(cadastrarTratamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(anoFimTratamentoSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(anoFimTratamentoLabel)))))
                    .addComponent(animalTratamentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cadastrarTratamentoPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(cadastrarTratamentoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        cadastrarTratamentoPanelLayout.setVerticalGroup(
            cadastrarTratamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarTratamentoPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(cadastrarTratamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesInicioTratamentoLabel)
                    .addComponent(anoInicioTratamentoLabel)
                    .addComponent(dataInicioLabel)
                    .addComponent(diaInicioTratamentoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarTratamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaInicioTratamentoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesInicioTratamentoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoInicioTratamentoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastrarTratamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaFimTratamentoLabel)
                    .addComponent(mesFimTratamentoLabel)
                    .addComponent(anoFimTratamentoLabel)
                    .addComponent(dataFimTratamentoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarTratamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaFimTratamentoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesFimTratamentoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoFimTratamentoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(animalTratamentoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(animalTratamentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastrarTratamentoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        tratamentoTabbedPane.addTab("Cadastrar Tratamento", cadastrarTratamentoPanel);

        tratamentoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Data início", "Data fim", "Animal"
            }
        ));
        tratamentoScrollPane.setViewportView(tratamentoTable);

        javax.swing.GroupLayout tratamentoPanelLayout = new javax.swing.GroupLayout(tratamentoPanel);
        tratamentoPanel.setLayout(tratamentoPanelLayout);
        tratamentoPanelLayout.setHorizontalGroup(
            tratamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tratamentoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tratamentoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tratamentoTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tratamentoPanelLayout.setVerticalGroup(
            tratamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tratamentoTabbedPane)
            .addGroup(tratamentoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tratamentoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Tratamento", tratamentoPanel);

        logoIcon.setIcon(new ImageIcon("src/main/java/com/vet/img/clinicaveterinaria.png")); // NOI18N
        logoIcon.setMaximumSize(new java.awt.Dimension(32, 32));
        logoIcon.setMinimumSize(new java.awt.Dimension(32, 32));
        logoIcon.setPreferredSize(new java.awt.Dimension(64, 64));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void especieAnimalComboBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_especieAnimalComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especieAnimalComboBoxActionPerformed

    private void tutorComboBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_tutorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tutorComboBoxActionPerformed

    private void consultaExameComboBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_consultaExameComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaExameComboBoxActionPerformed

    private void animalTratamentoComboBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_animalTratamentoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animalTratamentoComboBoxActionPerformed

    private void atualizarClienteComboBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_atualizarClienteComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizarClienteComboBoxActionPerformed

    private void atualizarAnimalComboBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_atualizarAnimalComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizarAnimalComboBoxActionPerformed

    private void atualizarTutorComboBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_atualizarTutorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizarTutorComboBoxActionPerformed

    private void atualizarEspecieComboBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_atualizarEspecieComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizarEspecieComboBoxActionPerformed

    private void atualizarVeterinarioComboBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_atualizarVeterinarioComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizarVeterinarioComboBoxActionPerformed

    private void sexoAnimalComboBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_sexoAnimalComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoAnimalComboBoxActionPerformed

    private void atualizarNomeClienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarNomeClienteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizarNomeClienteTextFieldActionPerformed

    private void nomeVeterinarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeVeterinarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeVeterinarioTextFieldActionPerformed

    private void veterinarioConsultaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veterinarioConsultaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veterinarioConsultaComboBoxActionPerformed

    private void tratamentoConsultaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tratamentoConsultaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tratamentoConsultaComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel animalPanel;
    private javax.swing.JScrollPane animalScrollPane;
    private javax.swing.JTabbedPane animalTabbedPane;
    private javax.swing.JTable animalTable;
    private javax.swing.JComboBox<String> animalTratamentoComboBox;
    private javax.swing.JLabel animalTratamentoLabel;
    private javax.swing.JLabel anoConsultaLabel;
    private javax.swing.JSpinner anoConsultaSpinner;
    private javax.swing.JLabel anoFimTratamentoLabel;
    private javax.swing.JSpinner anoFimTratamentoSpinner;
    private javax.swing.JLabel anoInicioTratamentoLabel;
    private javax.swing.JSpinner anoInicioTratamentoSpinner;
    private javax.swing.JButton atualizarAnimalButton;
    private javax.swing.JComboBox<String> atualizarAnimalComboBox;
    private javax.swing.JLabel atualizarAnimalLabel;
    private javax.swing.JPanel atualizarAnimalPanel;
    private javax.swing.JLabel atualizarCepClienteLabel;
    private javax.swing.JTextField atualizarCepClienteTextField;
    private javax.swing.JLabel atualizarCepVeterinarioLabel;
    private javax.swing.JTextField atualizarCepVeterinarioTextField;
    private javax.swing.JButton atualizarClienteButton;
    private javax.swing.JComboBox<String> atualizarClienteComboBox;
    private javax.swing.JLabel atualizarClienteLabel;
    private javax.swing.JPanel atualizarClientePanel;
    private javax.swing.JLabel atualizarEmailClienteLabel;
    private javax.swing.JTextField atualizarEmailClienteTextField;
    private javax.swing.JLabel atualizarEmailVeterinarioLabel;
    private javax.swing.JTextField atualizarEmailVeterinarioTextField;
    private javax.swing.JLabel atualizarEnderecoClienteLabel;
    private javax.swing.JTextField atualizarEnderecoClienteTextField;
    private javax.swing.JLabel atualizarEnderecoVeterinarioLabel;
    private javax.swing.JTextField atualizarEnderecoVeterinarioTextField;
    private javax.swing.JComboBox<String> atualizarEspecieComboBox;
    private javax.swing.JLabel atualizarEspecieLabel;
    private javax.swing.JLabel atualizarIdadeAnimalLabel;
    private javax.swing.JSpinner atualizarIdadeAnimalSpinner;
    private javax.swing.JLabel atualizarNomeAnimalLabel;
    private javax.swing.JTextField atualizarNomeAnimalTextField;
    private javax.swing.JLabel atualizarNomeClienteLabel;
    private javax.swing.JTextField atualizarNomeClienteTextField;
    private javax.swing.JLabel atualizarNomeVeterinarioLabel;
    private javax.swing.JTextField atualizarNomeVeterinarioTextField;
    private javax.swing.JComboBox<String> atualizarSexoAnimalComboBox;
    private javax.swing.JLabel atualizarSexoAnimalLabel;
    private javax.swing.JLabel atualizarTelefoneClienteLabel;
    private javax.swing.JTextField atualizarTelefoneClienteTextField;
    private javax.swing.JLabel atualizarTelefoneVeterinarioLabel;
    private javax.swing.JTextField atualizarTelefoneVeterinarioTextField;
    private javax.swing.JComboBox<String> atualizarTutorComboBox;
    private javax.swing.JLabel atualizarTutorLabel;
    private javax.swing.JPanel atualizarVeterinario;
    private javax.swing.JButton atualizarVeterinarioButton;
    private javax.swing.JComboBox<String> atualizarVeterinarioComboBox;
    private javax.swing.JLabel atualizarVeterinarioLabel;
    private javax.swing.JButton cadastrarAnimalButton;
    private javax.swing.JPanel cadastrarAnimalPanel;
    private javax.swing.JButton cadastrarClienteButton;
    private javax.swing.JPanel cadastrarClientePanel;
    private javax.swing.JPanel cadastrarConsulta;
    private javax.swing.JButton cadastrarConsultaButton;
    private javax.swing.JButton cadastrarEspecieButton;
    private javax.swing.JPanel cadastrarEspeciesPanel;
    private javax.swing.JButton cadastrarExameButton;
    private javax.swing.JPanel cadastrarExamePanel;
    private javax.swing.JButton cadastrarTratamentoButton;
    private javax.swing.JPanel cadastrarTratamentoPanel;
    private javax.swing.JPanel cadastrarVeterinario;
    private javax.swing.JButton cadastrarVeterinarioButton;
    private javax.swing.JLabel cepClienteLabel;
    private javax.swing.JTextField cepClienteTextField;
    private javax.swing.JLabel cepVeterinarioLabel;
    private javax.swing.JTextField cepVeterinarioTextField;
    private javax.swing.JPanel clientePanel;
    private javax.swing.JScrollPane clienteScrollPane;
    private javax.swing.JTabbedPane clienteTabbedPane;
    private javax.swing.JTable clienteTable;
    private javax.swing.JComboBox<String> consultaExameComboBox;
    private javax.swing.JLabel consultaExameLabel;
    private javax.swing.JPanel consultaPanel;
    private javax.swing.JScrollPane consultaScrollPane;
    private javax.swing.JTabbedPane consultaTabbedPane;
    private javax.swing.JTable consultaTable;
    private javax.swing.JLabel dataConsultaLabel;
    private javax.swing.JLabel dataFimTratamentoLabel;
    private javax.swing.JLabel dataInicioLabel;
    private javax.swing.JScrollPane descricaoCadastrarExamePane;
    private javax.swing.JLabel descricaoExameLabel;
    private javax.swing.JTextArea descricaoExameTextArea;
    private javax.swing.JLabel diaConsultaLabel;
    private javax.swing.JSpinner diaConsultaSpinner;
    private javax.swing.JLabel diaFimTratamentoLabel;
    private javax.swing.JSpinner diaFimTratamentoSpinner;
    private javax.swing.JLabel diaInicioTratamentoLabel;
    private javax.swing.JSpinner diaInicioTratamentoSpinner;
    private javax.swing.JLabel emailClienteLabel;
    private javax.swing.JTextField emailClienteTextField;
    private javax.swing.JLabel emailVeterinarioLabel;
    private javax.swing.JTextField emailVeterinarioTextField;
    private javax.swing.JLabel enderecoClienteLabel;
    private javax.swing.JTextField enderecoClienteTextField;
    private javax.swing.JLabel enderecoVeterinarioLabel;
    private javax.swing.JTextField enderecoVeterinarioTextField;
    private javax.swing.JComboBox<String> especieAnimalComboBox;
    private javax.swing.JLabel especieAnimalLabel;
    private javax.swing.JPanel examePanel;
    private javax.swing.JScrollPane exameScrollPane;
    private javax.swing.JTabbedPane exameTabbedPane;
    private javax.swing.JTable exameTable;
    private javax.swing.JLabel idadeAnimalLabel;
    private javax.swing.JSpinner idadeAnimalSpinner;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JLabel mesConsultaLabel;
    private javax.swing.JSpinner mesConsultaSpinner;
    private javax.swing.JLabel mesFimTratamentoLabel;
    private javax.swing.JSpinner mesFimTratamentoSpinner;
    private javax.swing.JLabel mesInicioTratamentoLabel;
    private javax.swing.JSpinner mesInicioTratamentoSpinner;
    private javax.swing.JLabel nomeAnimalLabel;
    private javax.swing.JTextField nomeAnimalTextField;
    private javax.swing.JLabel nomeClienteLabel;
    private javax.swing.JTextField nomeClienteTextField;
    private javax.swing.JLabel nomeEspecieLabel;
    private javax.swing.JTextField nomeEspecieTextField;
    private javax.swing.JLabel nomeVeterinarioLabel;
    private javax.swing.JTextField nomeVeterinarioTextField;
    private javax.swing.JScrollPane relatoCadastrarConsultaScrollPane;
    private javax.swing.JLabel relatoConsultaLabel;
    private javax.swing.JTextArea relatoConsultaTextArea;
    private javax.swing.JComboBox<String> sexoAnimalComboBox;
    private javax.swing.JLabel sexoAnimalLabel;
    private javax.swing.JLabel telefoneClienteLabel;
    private javax.swing.JTextField telefoneClienteTextField;
    private javax.swing.JLabel telefoneVeterinarioLabel;
    private javax.swing.JTextField telefoneVeterinarioTextField;
    private javax.swing.JComboBox<String> tratamentoConsultaComboBox;
    private javax.swing.JLabel tratamentoConsultaLabel;
    private javax.swing.JPanel tratamentoPanel;
    private javax.swing.JScrollPane tratamentoScrollPane;
    private javax.swing.JTabbedPane tratamentoTabbedPane;
    private javax.swing.JTable tratamentoTable;
    private javax.swing.JComboBox<String> tutorComboBox;
    private javax.swing.JLabel tutorLabel;
    private javax.swing.JComboBox<String> veterinarioConsultaComboBox;
    private javax.swing.JLabel veterinarioConsultaLabel;
    private javax.swing.JPanel veterinarioPanel;
    private javax.swing.JScrollPane veterinarioScrollPane;
    private javax.swing.JTabbedPane veterinarioTabbedPane;
    private javax.swing.JTable veterinarioTable;
    // End of variables declaration//GEN-END:variables
}
